lane :increment do
increment_version_code(gradle_file_path:"app/build.gradle")
end

before_all do 
ensure_git_branch
ensure_git_branch_clean
end

private_lane :increment_version do |options
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/ 
    s = File.read(path)
    versionCode = s[re, 1].to_i 
    #1 here represent capture group , capture group is a part of the returned string from regex .To Capture We have to put the part of regular expression in round paranthesis ( )
    s[re, 1] = (versionCode + 1).to_s
  
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end
  